version: '3'
services:
  ctfsuite:
    build: .
    ports:
      - "3301:3301"
      - "3302:3302"
      - "3303:3303"
      - "3304:3304"
      - "3305:3305"
      - "3306:3306"
      - "3307:3307"
      - "3308:3308"
      - "3309:3309"
    expose:
      - "3301"
      - "3302"
      - "3303"
      - "3304"
      - "3305"
      - "3306"
      - "3307"
      - "3308"
      - "3309"
    volumes:
      - .:/ctf
      - ./.zsh_history:/host/.zsh_history
    privileged: true
    command: tail -f /dev/null
