version: '3'
services:
  openvpn-hackthebox:
    build: docker-images/openvpn-client
    networks:
      ctfsuite-net:
        ipv4_address: 172.28.28.2
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
      net.ipv6.conf.lo.disable_ipv6: 0
      net.ipv4.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - ./hackthebox.ovpn:/openvpn/ovpn.ovpn
  tinyproxy:
    build: docker-images/tinyproxy
    networks:
      ctfsuite-net:
        ipv4_address: 172.28.28.3
    cap_add:
      - NET_ADMIN
    ports:
      - "3301:3301"
    expose:
      - "3301"
  ctfsuite:
    build: docker-images/ctfsuite
    networks:
      ctfsuite-net:
        ipv4_address: 172.28.28.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pwd:/pwd
      - home:/root
      # - ./.bash_history:/root/.bash_history
    # command: tail -f /dev/null
    tty: true
networks:
  ctfsuite-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.28.0/24
volumes:
  home:
